language: r
cache: packages
os:
- linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra
- tlmgr install standalone
addons:
  apt:
    update:
    - true
    sources:
    - sourceline: ppa:opencpu/imagemagick
    packages:
    - libmagick++-dev
r_github_packages:
- yonicd/covrpage
- metrumresearchgroup/pkgdown
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: c0EzDlMgLwgeMEaLHh0h/wBfLt/ZSXTQFF1fTrFiM+2vevlmjuIExbPxvjvyxNvx2s7KkSZazXtwy/A5UstodjEl1FAp/FUNxELAHF6EPd98y3jAYrBOwR1/1213dDntbOruXc1cq+hsOTDBGaQi1Qji7BgbxONOGDJ0MwTt54YnJ+WqV2ZuUHC9y7XnCIoKEE8vQu2yO53M3h9YTjA9y11Ba6KC2el2m3K2dMoHNTdxE/3wvdxChd2BEUgvQogOh3v0G3mYP7Hwo7LHkTjwoLN6Sya6x8TCHphdnnD/u1TgaiWGefZx1R+sANKpqJukb+1uNQCO5tp/K10/XzFhBlOqjlqhaFYcNapfK+nF5/QEEpyLYFvuTvER7NcVny1v525QL80mAEJKWw4MxMRKwnxpPNxeKyYqvC44iYmY2HZjWneGC5KRfi5Y/fDMCsRiQwJGJqRQTpNv7I2kAAP+elOmeGKdT1HGFofdGl34XL2NIiBGo6jgN3qNvzUxXq5TAMRcF1Msl+nyFoomDhqhNo5IsLIcmrNamWwQMxXikuBM95fdcPTwNF6zudj7rR3uTQvUezNo29emL5LN4T/9GYd2drPok+KselDMXDlZwvQXKs1jFc6BMmxbHY1jRllF2ZI0BFi0tpGueQNIcbn6lYVBJuIRpoh7hKCP3mBAkKs=
notifications:
  slack:
    secure: YDWEobNljHKrq1H+Ejw2s1BX1KGnuI1tATejJ6STXITiStzXvh9OhuNi02yIB0wHI+JGkHMKgKk3SeBingDSzI9weL4ZadGJUO/L9lzfiRCGnzxm+tqchUZNOBX1aFnBi9Aek0ERQjYSgpml0ZdR9BQ2y98yQvb6+yxeefIePPKAon8ZB2npKOtkRGXJC5HNja8sizp3d4k/SEGd7g/J4Jz60F5UHjWzjtBzXTX1AKYUtFLBXj0BQH3uZvWSYHd+fCYqbj8HYtDcmOacFYoXsktSEYhpU1TBT9WB/O4i6VICm89Khfu3h18lFvFFgQA654rjBcNA+RNz9KLUg/4W5KaV2O91ialjgJ/Uy/X0IOEogjIG4ypKH2N/5/l0xHlRRJMYa9dcaPoXTrY0RXPNenDKAotClF/ue01GLa661fcX8LO8WlRSjEjg+zcil06QG9DIzpN8yFutoHFKXkDgdDmbf1niYsN46T28lcNvPelgBY0/tISM6hUGl2J4Jx3mBdmiHUXcRXvXHzS6PGw+CmQb5HqfTnop7+mJBr9sDowTKbBRSF09ge4keU7CFzXQZtUyOIzfh+BTS48BhcvnwH8P2hbzcnryeSBD06H1Y9oAsazGD/3deMDY4IDS1D3RFvouj2tr63KWYFGYcj6lWLoRbYZIOdVPGGhjI3zGeW8=
