on:
  push

name: R-linux

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "!contains(github.event.head_commit.message, 'skip linux')"
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", args: "--no-manual" }
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-tinytex@master

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: setup config
        run: |
          dotR <- file.path(Sys.getenv("HOME"), ".R")
          if (!file.exists(dotR)) dir.create(dotR)
          M <- file.path(dotR, ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"))
          if (!file.exists(M)) file.create(M)
          magick_settings <- c(
            'PKG_CPPFLAGS = Magick++-config --cppflags',
            'PKG_CXXFLAGS = Magick++-config --cxxflags',
            'PKG_LIBS = Magick++-config --ldflags --libs'
          )
          cat(magick_settings,file = M, sep = "\n", append = TRUE) 
          readLines(M)
        shell: Rscript {0}
        
      - name: Install magick libs
        run: |
          sudo add-apt-repository ppa:cran/imagemagick
          sudo apt-get -qq update
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install libmagick++-dev librsvg2-dev libwebp-dev libpoppler-cpp-dev libtesseract-dev libleptonica-dev tesseract-ocr-eng libfftw3-dev cargo ghostscript gsfonts
          export PATH; PATH="$HOME/ImageMagick/bin:$PATH"
          export LD_LIBRARY_PATH="$HOME/ImageMagick-6.9.7-4/lib"
          convert logo: logo.gif
